url: "http://www.scottkilts.com"
description: you are the spacetimedistortion
baseurl: ""
title: scott kilts
email: sjkilts@gmail.com
permalink: /:categories/:title/
markdown: Kramdown

excerpt_separator: <!--more-->

users:
  - login: "sjkilts"
    user: "Scott Kilts"

include: 
  - _notes

prose:
  siteurl: "http://www.scottkilts.com"
