url: "http://www.scottkilts.com"
description: you are the spacetimedistortion
baseurl: /
title: scott kilts
email: sjkilts@gmail.com
permalink: /:categories/:title/
markdown: CommonMark

plugins:
          - jekyll-paginate
          - jekyll-sitemap

commonmark:
  options: ["FOOTNOTES", "SMART"]
  extensions: ["strikethrough", "autolink", "table", "tasklist", "tagfilter"]

excerpt_separator: <!--more-->

paginate: 6
paginate_path: "_posts/page:num"
defaults:
  -
    scope:
      path: "post" # an empty string here means all files in the project 
    values:
      layout: "post"
      category: "post"

prose:
  rooturl: '_posts'
  siteurl: 'http://sjkilts.github.io/'
  relativeLinks: ''
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "post"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "photo_url"
        field:
          element: "text"
          label: "450x450 Picture Thumb for index"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"
users:
  - login: "sjkilts"
    user: "Scott Kilts"
